[[language]]
name = "verilog"
language-server = { command = "svls" }

[[language]]
name = "scheme"
file-types = [ "lisp", "cl", "el", "mud", "asd" ]
language-server = { command = "cl-lsp", args = [ "stdio" ] }

[[language]]
name = "markdown"
roots = [".marksman.toml"]
language-server = { command = "marksman", args = ["server"] }
