theme = "fleetish"

[editor]
line-number = "relative"
scrolloff = 5
idle-timeout = 0
auto-pairs = false
color-modes = true
cursorline = true
true-color = true

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "all"
characters = { tab = "▸", newline = "◂" }

